#!/usr/bin python3
import re
import sys
import socket
import select

server = socket.socket()
server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
if len(sys.argv) != 2:
    print("Usage: ./chatserver <server-ip>:<port>")
    sys.exit(1)
args = sys.argv[1].split(':')
ip = str(args[0])
port = int(args[1])

# bind the (ip,port) to the server
server.bind((ip, port))
# listen for atmost 100 connections
server.listen(100)
clients = [server]
clients_hashmap = {}
clients_in_queue = []


def broadcast(msg, conn):
    for client in clients_hashmap.keys():
        if client != conn:
            print("Broadcasting")
            try:
                client.sendall(msg.encode('ascii'))
            except:
                client.close()
                del clients_hashmap[client]
                clients.remove(client)


def main():
    print("Chat Server running")
    while True:
        readsockets, writesockets, errorsockets = select.select(clients, [], [])
        for socket in readsockets:
            if socket == server:
                # accept a new connection
                newclient, addr = server.accept()
                newclient.sendall("Hello 1".encode('ascii'))
                clients.append(newclient)
                clients_in_queue.append(newclient)
            elif socket in clients_in_queue:
                try:
                    name_load = socket.recv(1024).decode('ascii')
                    if name_load:
                        check = re.search(r'NICK\s(\S*)', name_load)
                        name = str(check.group(1))
                        if len(name) > 12:
                            socket.sendall("ERROR nickname should not be greater than 12 characters ".encode('ascii'))
                        elif (re.search(r'!', name) or re.search(r'@', name) or re.search(r'#', name) or re.search(
                                r'\$', name) or re.search(r'%', name) or re.search(r'\*', name) or re.search(r'\^',
                                                                                                             name)):
                            socket.sendall("ERROR don't use special characters in the nick name")
                        elif check:
                            socket.sendall(("OK\n".encode('ascii')))
                            clients_hashmap[socket] = name
                            clients_in_queue.remove(socket)
                        else:
                            if name_load[:3] == "MSG":
                                socket.sendall("ERROR no nick set".encode('ascii'))
                            elif name_load[-4:] == 'NICK':
                                socket.sendall("ERROR malformed command".encode('ascii'))
                            else:
                                socket.sendall("ERROR malformed command".encode('ascii'))
                    else:
                        socket.close()
                        clients.remove(socket)
                        clients_in_queue.remove(socket)
                except:
                    continue
            elif socket in clients_hashmap.keys():
                try:
                    message = socket.recv(1024).decode('ascii')
                    if message:
                        check = message[:3] == 'MSG'
                        if (len(message)) > 259:
                            socket.sendall("ERROR message length should not exceed 256 characters".encode('ascii'))
                        elif check:
                            message_load = "MSG " + str(clients_hashmap[socket]) + ": " + message[4:]
                            broadcast(message_load, socket)
                        else:
                            socket.sendall("ERROR malformed command".encode('ascii'))
                    else:
                        socket.close()
                        clients.remove(socket)
                        del clients_hashmap[socket]
                except:
                    continue
    server.close()


if __name__ == '__main__':
    main()
